[package]
name = "ethercat-master"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "EtherCAT Master"

[dependencies]
log = "0.4"
bitfield = { git="https://github.com/dzamlo/rust-bitfield", rev = "5a517f8" }
bit_field = "0.10"
paste = "1.0.7"
void = "1"
nb = "1"
num_enum = "0.5.7"

[dev-dependencies]
env_logger = "0.9.0"
pnet_datalink = "0.31.0"
smoltcp = { version = "0.8", default-features = false, features = ["proto-ipv4", "medium-ethernet","socket-raw"] }