[package]
name = "ethercat-master"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "EtherCat Master"

[dependencies]
log = "0.4"
heapless = "0.7"
bitfield = { git="https://github.com/dzamlo/rust-bitfield", rev = "5a517f8" }
bit_field = "0.10"
paste = "1.0.7"
#fugit = "0.3.5"
#embedded-hal = "0.2.7"
void = "1"
nb = "1"
hash32 = "0.3"
num_enum = "0.5.7"

[dev-dependencies]
env_logger = "0.9.0"
pnet_datalink = "0.31.0"
void = "1"
smoltcp = { version = "0.8", default-features = false, features = ["proto-ipv4", "medium-ethernet","socket-raw"] }