#[derive(Debug, Clone)]
pub enum CommonError {
    DeviceErrorTx,
    DeviceErrorRx,
    BufferExhausted,
    BadPacket,
    //UnspcifiedTimerError,
    //ReceiveTimeout,
    LostCommand,
    UnexpectedWKC(u16),
}

// TODO: 整理する
//#[derive(Debug, Clone)]
//pub enum Error {
//    LargeData,
//    SmallBuffer,
//    WkcNeq(u16, u16),
//    RxError(u8),
//    UnexpectedPacket,
//    EEPROMNotOperation,
//    AlStateTransfer(u16, AlState),
//    AlStateTimeout(u64, AlState),
//    TooManySlave(usize),
//    UnimplementedFeature,
//    NotFoundSlaves,
//    NotExistSlave(u16),
//    CannotAccessEEPROM,
//    EEPROMStatusError,
//    EEPROMBusyTimeout,
//    MailboxCounterError,
//    MailboxAbort(AbortCode),
//    UnexpectedMailbox(u8),
//    SdoMaxDataLength,
//    MailboxError(MailboxErrorDetail),
//    MaxRxPdo,
//    MaxTxPdo,
//    Sync0Timeout(u64),
//    MailboxDisable,
//    MailboxTimeout(u64),
//    UnexpectedAlState(AlState, AlState),
//    NotRecieveEtherCatFrame,
//    InvalidCommand,
//    MaxMailboxLength,
//    UnableToRecievePacket,
//    UnableToSendPacket,
//}
